services:
  - type: web
    name: FlaskBlog
    # other necessary configuration options like build and start commands
    env: python
    postDeployCommand: flask --app main.py create-admin "$ADMIN_EMAIL" "$ADMIN_PASSWORD" "$ADMIN_NAME"
